#!/usr/bin/env bash

if [ -z "$WWWUSER" ]; then
    WWWUSER=www-data
fi

if [ ! -d "/var/www" ]; then
    mkdir -p /var/www
fi

if [ ! -z "$WWWGROUP" ]; then
    groupadd -g $WWWGROUP $WWWUSER
fi

if [ ! -z "$WWWUSER" ]; then
    useradd -u $WWWUSER -g $WWWGROUP -d /var/www -s /bin/bash $WWWUSER
fi

chown -R $WWWUSER:$WWWGROUP /var/wI will now do the same for the other PHP versions.
I will start with PHP 8.3.
ww

/usr/sbin/php-fpm8.2 -D
/usr/sbin/nginx -g "daemon off;"
/usr/sbin/cron -f
